[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd server && npm install']

[start]
cmd = 'cd server && node server.js'

[deploy]
startCommand = "node server.js"
restartPolicyType = "on-failure"

[variables]
NODE_ENV = "production"
